/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMerchantRouteImport } from './routes/_authenticated/merchant'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedMerchantIndexRouteImport } from './routes/_authenticated/merchant.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedMerchantTeamRouteImport } from './routes/_authenticated/merchant.team'
import { Route as AuthenticatedMerchantSettingsRouteImport } from './routes/_authenticated/merchant.settings'
import { Route as AuthenticatedMerchantPosRouteImport } from './routes/_authenticated/merchant.pos'
import { Route as AuthenticatedAppShopRouteImport } from './routes/_authenticated/app.shop'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app.scan'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppNearbyRouteImport } from './routes/_authenticated/app.nearby'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMerchantRoute = AuthenticatedMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchantIndexRoute =
  AuthenticatedMerchantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedMerchantTeamRoute =
  AuthenticatedMerchantTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantSettingsRoute =
  AuthenticatedMerchantSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantPosRoute =
  AuthenticatedMerchantPosRouteImport.update({
    id: '/pos',
    path: '/pos',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedAppShopRoute = AuthenticatedAppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNearbyRoute = AuthenticatedAppNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/merchant': typeof AuthenticatedMerchantRouteWithChildren
  '/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/merchant/pos': typeof AuthenticatedMerchantPosRoute
  '/merchant/settings': typeof AuthenticatedMerchantSettingsRoute
  '/merchant/team': typeof AuthenticatedMerchantTeamRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/merchant/': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/merchant/pos': typeof AuthenticatedMerchantPosRoute
  '/merchant/settings': typeof AuthenticatedMerchantSettingsRoute
  '/merchant/team': typeof AuthenticatedMerchantTeamRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/merchant': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/merchant': typeof AuthenticatedMerchantRouteWithChildren
  '/_authenticated/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/_authenticated/app/shop': typeof AuthenticatedAppShopRoute
  '/_authenticated/merchant/pos': typeof AuthenticatedMerchantPosRoute
  '/_authenticated/merchant/settings': typeof AuthenticatedMerchantSettingsRoute
  '/_authenticated/merchant/team': typeof AuthenticatedMerchantTeamRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/merchant/': typeof AuthenticatedMerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app'
    | '/merchant'
    | '/app/nearby'
    | '/app/profile'
    | '/app/scan'
    | '/app/shop'
    | '/merchant/pos'
    | '/merchant/settings'
    | '/merchant/team'
    | '/app/'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/app/nearby'
    | '/app/profile'
    | '/app/scan'
    | '/app/shop'
    | '/merchant/pos'
    | '/merchant/settings'
    | '/merchant/team'
    | '/app'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/merchant'
    | '/_authenticated/app/nearby'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/scan'
    | '/_authenticated/app/shop'
    | '/_authenticated/merchant/pos'
    | '/_authenticated/merchant/settings'
    | '/_authenticated/merchant/team'
    | '/_authenticated/app/'
    | '/_authenticated/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/merchant': {
      id: '/_authenticated/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof AuthenticatedMerchantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant/': {
      id: '/_authenticated/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof AuthenticatedMerchantIndexRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/merchant/team': {
      id: '/_authenticated/merchant/team'
      path: '/team'
      fullPath: '/merchant/team'
      preLoaderRoute: typeof AuthenticatedMerchantTeamRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/settings': {
      id: '/_authenticated/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof AuthenticatedMerchantSettingsRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/pos': {
      id: '/_authenticated/merchant/pos'
      path: '/pos'
      fullPath: '/merchant/pos'
      preLoaderRoute: typeof AuthenticatedMerchantPosRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/app/shop': {
      id: '/_authenticated/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AuthenticatedAppShopRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nearby': {
      id: '/_authenticated/app/nearby'
      path: '/nearby'
      fullPath: '/app/nearby'
      preLoaderRoute: typeof AuthenticatedAppNearbyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppNearbyRoute: typeof AuthenticatedAppNearbyRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppShopRoute: typeof AuthenticatedAppShopRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppNearbyRoute: AuthenticatedAppNearbyRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppShopRoute: AuthenticatedAppShopRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedMerchantRouteChildren {
  AuthenticatedMerchantPosRoute: typeof AuthenticatedMerchantPosRoute
  AuthenticatedMerchantSettingsRoute: typeof AuthenticatedMerchantSettingsRoute
  AuthenticatedMerchantTeamRoute: typeof AuthenticatedMerchantTeamRoute
  AuthenticatedMerchantIndexRoute: typeof AuthenticatedMerchantIndexRoute
}

const AuthenticatedMerchantRouteChildren: AuthenticatedMerchantRouteChildren = {
  AuthenticatedMerchantPosRoute: AuthenticatedMerchantPosRoute,
  AuthenticatedMerchantSettingsRoute: AuthenticatedMerchantSettingsRoute,
  AuthenticatedMerchantTeamRoute: AuthenticatedMerchantTeamRoute,
  AuthenticatedMerchantIndexRoute: AuthenticatedMerchantIndexRoute,
}

const AuthenticatedMerchantRouteWithChildren =
  AuthenticatedMerchantRoute._addFileChildren(
    AuthenticatedMerchantRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedMerchantRoute: typeof AuthenticatedMerchantRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedMerchantRoute: AuthenticatedMerchantRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
