/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalImprintRouteImport } from './routes/legal.imprint'
import { Route as LegalGdprRouteImport } from './routes/legal.gdpr'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalComplaintsRouteImport } from './routes/legal.complaints'
import { Route as LegalAmlRouteImport } from './routes/legal.aml'
import { Route as LegalAccessibilityRouteImport } from './routes/legal.accessibility'
import { Route as FeaturesStaffRouteImport } from './routes/features.staff'
import { Route as FeaturesPartnersRouteImport } from './routes/features.partners'
import { Route as FeaturesMerchantsRouteImport } from './routes/features.merchants'
import { Route as FeaturesEnterpriseRouteImport } from './routes/features.enterprise'
import { Route as FeaturesDevelopersRouteImport } from './routes/features.developers'
import { Route as FeaturesConsumersRouteImport } from './routes/features.consumers'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedRewardsV4RouteImport } from './routes/_authenticated/rewards-v4'
import { Route as AuthenticatedRewardsScenarioLabRouteImport } from './routes/_authenticated/rewards-scenario-lab'
import { Route as AuthenticatedRewardsProductionRouteImport } from './routes/_authenticated/rewards-production'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedPilotOperationsRouteImport } from './routes/_authenticated/pilot-operations'
import { Route as AuthenticatedMerchantOnboardingRouteImport } from './routes/_authenticated/merchant-onboarding'
import { Route as AuthenticatedMerchantRouteImport } from './routes/_authenticated/merchant'
import { Route as AuthenticatedLiabilityCentreRouteImport } from './routes/_authenticated/liability-centre'
import { Route as AuthenticatedGoLiveReadinessRouteImport } from './routes/_authenticated/go-live-readiness'
import { Route as AuthenticatedCampaignStudioRouteImport } from './routes/_authenticated/campaign-studio'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMerchantIndexRouteImport } from './routes/_authenticated/merchant.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedMerchantTeamRouteImport } from './routes/_authenticated/merchant.team'
import { Route as AuthenticatedMerchantSettingsRouteImport } from './routes/_authenticated/merchant.settings'
import { Route as AuthenticatedMerchantRewardsRouteImport } from './routes/_authenticated/merchant.rewards'
import { Route as AuthenticatedMerchantPosRouteImport } from './routes/_authenticated/merchant.pos'
import { Route as AuthenticatedMerchantOffersRouteImport } from './routes/_authenticated/merchant.offers'
import { Route as AuthenticatedMerchantIntegrationsRouteImport } from './routes/_authenticated/merchant.integrations'
import { Route as AuthenticatedMerchantFundingRouteImport } from './routes/_authenticated/merchant.funding'
import { Route as AuthenticatedMerchantCampaignsRouteImport } from './routes/_authenticated/merchant.campaigns'
import { Route as AuthenticatedMerchantAnalyticsRouteImport } from './routes/_authenticated/merchant.analytics'
import { Route as AuthenticatedAppShopRouteImport } from './routes/_authenticated/app.shop'
import { Route as AuthenticatedAppScanRouteImport } from './routes/_authenticated/app.scan'
import { Route as AuthenticatedAppRewardsRouteImport } from './routes/_authenticated/app.rewards'
import { Route as AuthenticatedAppReferralsRouteImport } from './routes/_authenticated/app.referrals'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app.profile'
import { Route as AuthenticatedAppOffersRouteImport } from './routes/_authenticated/app.offers'
import { Route as AuthenticatedAppNotificationsRouteImport } from './routes/_authenticated/app.notifications'
import { Route as AuthenticatedAppNearbyRouteImport } from './routes/_authenticated/app.nearby'
import { Route as AuthenticatedAppClaimRouteImport } from './routes/_authenticated/app.claim'
import { Route as AuthenticatedAppBadgesRouteImport } from './routes/_authenticated/app.badges'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedAdminMerchantsRouteImport } from './routes/_authenticated/admin.merchants'
import { Route as AuthenticatedAdminClaimsRouteImport } from './routes/_authenticated/admin.claims'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as ApiPublicRewardsScheduledJobsRouteImport } from './routes/api/public/rewards.scheduled-jobs'
import { Route as ApiPublicRewardsHealthRouteImport } from './routes/api/public/rewards.health'
import { Route as ApiPublicRewardsEventsRouteImport } from './routes/api/public/rewards.events'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalGdprRoute = LegalGdprRouteImport.update({
  id: '/legal/gdpr',
  path: '/legal/gdpr',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalComplaintsRoute = LegalComplaintsRouteImport.update({
  id: '/legal/complaints',
  path: '/legal/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAmlRoute = LegalAmlRouteImport.update({
  id: '/legal/aml',
  path: '/legal/aml',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAccessibilityRoute = LegalAccessibilityRouteImport.update({
  id: '/legal/accessibility',
  path: '/legal/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesStaffRoute = FeaturesStaffRouteImport.update({
  id: '/features/staff',
  path: '/features/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesPartnersRoute = FeaturesPartnersRouteImport.update({
  id: '/features/partners',
  path: '/features/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesMerchantsRoute = FeaturesMerchantsRouteImport.update({
  id: '/features/merchants',
  path: '/features/merchants',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesEnterpriseRoute = FeaturesEnterpriseRouteImport.update({
  id: '/features/enterprise',
  path: '/features/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesDevelopersRoute = FeaturesDevelopersRouteImport.update({
  id: '/features/developers',
  path: '/features/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesConsumersRoute = FeaturesConsumersRouteImport.update({
  id: '/features/consumers',
  path: '/features/consumers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRewardsV4Route = AuthenticatedRewardsV4RouteImport.update({
  id: '/rewards-v4',
  path: '/rewards-v4',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsScenarioLabRoute =
  AuthenticatedRewardsScenarioLabRouteImport.update({
    id: '/rewards-scenario-lab',
    path: '/rewards-scenario-lab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRewardsProductionRoute =
  AuthenticatedRewardsProductionRouteImport.update({
    id: '/rewards-production',
    path: '/rewards-production',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPilotOperationsRoute =
  AuthenticatedPilotOperationsRouteImport.update({
    id: '/pilot-operations',
    path: '/pilot-operations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantOnboardingRoute =
  AuthenticatedMerchantOnboardingRouteImport.update({
    id: '/merchant-onboarding',
    path: '/merchant-onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMerchantRoute = AuthenticatedMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiabilityCentreRoute =
  AuthenticatedLiabilityCentreRouteImport.update({
    id: '/liability-centre',
    path: '/liability-centre',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoLiveReadinessRoute =
  AuthenticatedGoLiveReadinessRouteImport.update({
    id: '/go-live-readiness',
    path: '/go-live-readiness',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignStudioRoute =
  AuthenticatedCampaignStudioRouteImport.update({
    id: '/campaign-studio',
    path: '/campaign-studio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMerchantIndexRoute =
  AuthenticatedMerchantIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedMerchantTeamRoute =
  AuthenticatedMerchantTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantSettingsRoute =
  AuthenticatedMerchantSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantRewardsRoute =
  AuthenticatedMerchantRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantPosRoute =
  AuthenticatedMerchantPosRouteImport.update({
    id: '/pos',
    path: '/pos',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantOffersRoute =
  AuthenticatedMerchantOffersRouteImport.update({
    id: '/offers',
    path: '/offers',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantIntegrationsRoute =
  AuthenticatedMerchantIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantFundingRoute =
  AuthenticatedMerchantFundingRouteImport.update({
    id: '/funding',
    path: '/funding',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantCampaignsRoute =
  AuthenticatedMerchantCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedMerchantAnalyticsRoute =
  AuthenticatedMerchantAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedMerchantRoute,
  } as any)
const AuthenticatedAppShopRoute = AuthenticatedAppShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppScanRoute = AuthenticatedAppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRewardsRoute = AuthenticatedAppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReferralsRoute =
  AuthenticatedAppReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOffersRoute = AuthenticatedAppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNotificationsRoute =
  AuthenticatedAppNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppNearbyRoute = AuthenticatedAppNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClaimRoute = AuthenticatedAppClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBadgesRoute = AuthenticatedAppBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMerchantsRoute =
  AuthenticatedAdminMerchantsRouteImport.update({
    id: '/merchants',
    path: '/merchants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClaimsRoute =
  AuthenticatedAdminClaimsRouteImport.update({
    id: '/claims',
    path: '/claims',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicRewardsScheduledJobsRoute =
  ApiPublicRewardsScheduledJobsRouteImport.update({
    id: '/api/public/rewards/scheduled-jobs',
    path: '/api/public/rewards/scheduled-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRewardsHealthRoute = ApiPublicRewardsHealthRouteImport.update({
  id: '/api/public/rewards/health',
  path: '/api/public/rewards/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRewardsEventsRoute = ApiPublicRewardsEventsRouteImport.update({
  id: '/api/public/rewards/events',
  path: '/api/public/rewards/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/billing': typeof AuthenticatedBillingRoute
  '/campaign-studio': typeof AuthenticatedCampaignStudioRoute
  '/go-live-readiness': typeof AuthenticatedGoLiveReadinessRoute
  '/liability-centre': typeof AuthenticatedLiabilityCentreRoute
  '/merchant': typeof AuthenticatedMerchantRouteWithChildren
  '/merchant-onboarding': typeof AuthenticatedMerchantOnboardingRoute
  '/pilot-operations': typeof AuthenticatedPilotOperationsRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/rewards-production': typeof AuthenticatedRewardsProductionRoute
  '/rewards-scenario-lab': typeof AuthenticatedRewardsScenarioLabRoute
  '/rewards-v4': typeof AuthenticatedRewardsV4Route
  '/blog/$slug': typeof BlogSlugRoute
  '/features/consumers': typeof FeaturesConsumersRoute
  '/features/developers': typeof FeaturesDevelopersRoute
  '/features/enterprise': typeof FeaturesEnterpriseRoute
  '/features/merchants': typeof FeaturesMerchantsRoute
  '/features/partners': typeof FeaturesPartnersRoute
  '/features/staff': typeof FeaturesStaffRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/claims': typeof AuthenticatedAdminClaimsRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/badges': typeof AuthenticatedAppBadgesRoute
  '/app/claim': typeof AuthenticatedAppClaimRoute
  '/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/offers': typeof AuthenticatedAppOffersRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/merchant/analytics': typeof AuthenticatedMerchantAnalyticsRoute
  '/merchant/campaigns': typeof AuthenticatedMerchantCampaignsRoute
  '/merchant/funding': typeof AuthenticatedMerchantFundingRoute
  '/merchant/integrations': typeof AuthenticatedMerchantIntegrationsRoute
  '/merchant/offers': typeof AuthenticatedMerchantOffersRoute
  '/merchant/pos': typeof AuthenticatedMerchantPosRoute
  '/merchant/rewards': typeof AuthenticatedMerchantRewardsRoute
  '/merchant/settings': typeof AuthenticatedMerchantSettingsRoute
  '/merchant/team': typeof AuthenticatedMerchantTeamRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/merchant/': typeof AuthenticatedMerchantIndexRoute
  '/api/public/rewards/events': typeof ApiPublicRewardsEventsRoute
  '/api/public/rewards/health': typeof ApiPublicRewardsHealthRoute
  '/api/public/rewards/scheduled-jobs': typeof ApiPublicRewardsScheduledJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/campaign-studio': typeof AuthenticatedCampaignStudioRoute
  '/go-live-readiness': typeof AuthenticatedGoLiveReadinessRoute
  '/liability-centre': typeof AuthenticatedLiabilityCentreRoute
  '/merchant-onboarding': typeof AuthenticatedMerchantOnboardingRoute
  '/pilot-operations': typeof AuthenticatedPilotOperationsRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/rewards-production': typeof AuthenticatedRewardsProductionRoute
  '/rewards-scenario-lab': typeof AuthenticatedRewardsScenarioLabRoute
  '/rewards-v4': typeof AuthenticatedRewardsV4Route
  '/blog/$slug': typeof BlogSlugRoute
  '/features/consumers': typeof FeaturesConsumersRoute
  '/features/developers': typeof FeaturesDevelopersRoute
  '/features/enterprise': typeof FeaturesEnterpriseRoute
  '/features/merchants': typeof FeaturesMerchantsRoute
  '/features/partners': typeof FeaturesPartnersRoute
  '/features/staff': typeof FeaturesStaffRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog': typeof BlogIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/claims': typeof AuthenticatedAdminClaimsRoute
  '/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/app/badges': typeof AuthenticatedAppBadgesRoute
  '/app/claim': typeof AuthenticatedAppClaimRoute
  '/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/app/offers': typeof AuthenticatedAppOffersRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/scan': typeof AuthenticatedAppScanRoute
  '/app/shop': typeof AuthenticatedAppShopRoute
  '/merchant/analytics': typeof AuthenticatedMerchantAnalyticsRoute
  '/merchant/campaigns': typeof AuthenticatedMerchantCampaignsRoute
  '/merchant/funding': typeof AuthenticatedMerchantFundingRoute
  '/merchant/integrations': typeof AuthenticatedMerchantIntegrationsRoute
  '/merchant/offers': typeof AuthenticatedMerchantOffersRoute
  '/merchant/pos': typeof AuthenticatedMerchantPosRoute
  '/merchant/rewards': typeof AuthenticatedMerchantRewardsRoute
  '/merchant/settings': typeof AuthenticatedMerchantSettingsRoute
  '/merchant/team': typeof AuthenticatedMerchantTeamRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/merchant': typeof AuthenticatedMerchantIndexRoute
  '/api/public/rewards/events': typeof ApiPublicRewardsEventsRoute
  '/api/public/rewards/health': typeof ApiPublicRewardsHealthRoute
  '/api/public/rewards/scheduled-jobs': typeof ApiPublicRewardsScheduledJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/campaign-studio': typeof AuthenticatedCampaignStudioRoute
  '/_authenticated/go-live-readiness': typeof AuthenticatedGoLiveReadinessRoute
  '/_authenticated/liability-centre': typeof AuthenticatedLiabilityCentreRoute
  '/_authenticated/merchant': typeof AuthenticatedMerchantRouteWithChildren
  '/_authenticated/merchant-onboarding': typeof AuthenticatedMerchantOnboardingRoute
  '/_authenticated/pilot-operations': typeof AuthenticatedPilotOperationsRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/rewards-production': typeof AuthenticatedRewardsProductionRoute
  '/_authenticated/rewards-scenario-lab': typeof AuthenticatedRewardsScenarioLabRoute
  '/_authenticated/rewards-v4': typeof AuthenticatedRewardsV4Route
  '/blog/$slug': typeof BlogSlugRoute
  '/features/consumers': typeof FeaturesConsumersRoute
  '/features/developers': typeof FeaturesDevelopersRoute
  '/features/enterprise': typeof FeaturesEnterpriseRoute
  '/features/merchants': typeof FeaturesMerchantsRoute
  '/features/partners': typeof FeaturesPartnersRoute
  '/features/staff': typeof FeaturesStaffRoute
  '/legal/accessibility': typeof LegalAccessibilityRoute
  '/legal/aml': typeof LegalAmlRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/gdpr': typeof LegalGdprRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/claims': typeof AuthenticatedAdminClaimsRoute
  '/_authenticated/admin/merchants': typeof AuthenticatedAdminMerchantsRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRoute
  '/_authenticated/app/badges': typeof AuthenticatedAppBadgesRoute
  '/_authenticated/app/claim': typeof AuthenticatedAppClaimRoute
  '/_authenticated/app/nearby': typeof AuthenticatedAppNearbyRoute
  '/_authenticated/app/notifications': typeof AuthenticatedAppNotificationsRoute
  '/_authenticated/app/offers': typeof AuthenticatedAppOffersRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/referrals': typeof AuthenticatedAppReferralsRoute
  '/_authenticated/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/_authenticated/app/scan': typeof AuthenticatedAppScanRoute
  '/_authenticated/app/shop': typeof AuthenticatedAppShopRoute
  '/_authenticated/merchant/analytics': typeof AuthenticatedMerchantAnalyticsRoute
  '/_authenticated/merchant/campaigns': typeof AuthenticatedMerchantCampaignsRoute
  '/_authenticated/merchant/funding': typeof AuthenticatedMerchantFundingRoute
  '/_authenticated/merchant/integrations': typeof AuthenticatedMerchantIntegrationsRoute
  '/_authenticated/merchant/offers': typeof AuthenticatedMerchantOffersRoute
  '/_authenticated/merchant/pos': typeof AuthenticatedMerchantPosRoute
  '/_authenticated/merchant/rewards': typeof AuthenticatedMerchantRewardsRoute
  '/_authenticated/merchant/settings': typeof AuthenticatedMerchantSettingsRoute
  '/_authenticated/merchant/team': typeof AuthenticatedMerchantTeamRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/merchant/': typeof AuthenticatedMerchantIndexRoute
  '/api/public/rewards/events': typeof ApiPublicRewardsEventsRoute
  '/api/public/rewards/health': typeof ApiPublicRewardsHealthRoute
  '/api/public/rewards/scheduled-jobs': typeof ApiPublicRewardsScheduledJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/admin'
    | '/app'
    | '/billing'
    | '/campaign-studio'
    | '/go-live-readiness'
    | '/liability-centre'
    | '/merchant'
    | '/merchant-onboarding'
    | '/pilot-operations'
    | '/reconciliation'
    | '/rewards-production'
    | '/rewards-scenario-lab'
    | '/rewards-v4'
    | '/blog/$slug'
    | '/features/consumers'
    | '/features/developers'
    | '/features/enterprise'
    | '/features/merchants'
    | '/features/partners'
    | '/features/staff'
    | '/legal/accessibility'
    | '/legal/aml'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog/'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/merchants'
    | '/admin/tenants'
    | '/app/assistant'
    | '/app/badges'
    | '/app/claim'
    | '/app/nearby'
    | '/app/notifications'
    | '/app/offers'
    | '/app/profile'
    | '/app/referrals'
    | '/app/rewards'
    | '/app/scan'
    | '/app/shop'
    | '/merchant/analytics'
    | '/merchant/campaigns'
    | '/merchant/funding'
    | '/merchant/integrations'
    | '/merchant/offers'
    | '/merchant/pos'
    | '/merchant/rewards'
    | '/merchant/settings'
    | '/merchant/team'
    | '/admin/'
    | '/app/'
    | '/merchant/'
    | '/api/public/rewards/events'
    | '/api/public/rewards/health'
    | '/api/public/rewards/scheduled-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/billing'
    | '/campaign-studio'
    | '/go-live-readiness'
    | '/liability-centre'
    | '/merchant-onboarding'
    | '/pilot-operations'
    | '/reconciliation'
    | '/rewards-production'
    | '/rewards-scenario-lab'
    | '/rewards-v4'
    | '/blog/$slug'
    | '/features/consumers'
    | '/features/developers'
    | '/features/enterprise'
    | '/features/merchants'
    | '/features/partners'
    | '/features/staff'
    | '/legal/accessibility'
    | '/legal/aml'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/claims'
    | '/admin/merchants'
    | '/admin/tenants'
    | '/app/assistant'
    | '/app/badges'
    | '/app/claim'
    | '/app/nearby'
    | '/app/notifications'
    | '/app/offers'
    | '/app/profile'
    | '/app/referrals'
    | '/app/rewards'
    | '/app/scan'
    | '/app/shop'
    | '/merchant/analytics'
    | '/merchant/campaigns'
    | '/merchant/funding'
    | '/merchant/integrations'
    | '/merchant/offers'
    | '/merchant/pos'
    | '/merchant/rewards'
    | '/merchant/settings'
    | '/merchant/team'
    | '/admin'
    | '/app'
    | '/merchant'
    | '/api/public/rewards/events'
    | '/api/public/rewards/health'
    | '/api/public/rewards/scheduled-jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/billing'
    | '/_authenticated/campaign-studio'
    | '/_authenticated/go-live-readiness'
    | '/_authenticated/liability-centre'
    | '/_authenticated/merchant'
    | '/_authenticated/merchant-onboarding'
    | '/_authenticated/pilot-operations'
    | '/_authenticated/reconciliation'
    | '/_authenticated/rewards-production'
    | '/_authenticated/rewards-scenario-lab'
    | '/_authenticated/rewards-v4'
    | '/blog/$slug'
    | '/features/consumers'
    | '/features/developers'
    | '/features/enterprise'
    | '/features/merchants'
    | '/features/partners'
    | '/features/staff'
    | '/legal/accessibility'
    | '/legal/aml'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/gdpr'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/blog/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/claims'
    | '/_authenticated/admin/merchants'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/badges'
    | '/_authenticated/app/claim'
    | '/_authenticated/app/nearby'
    | '/_authenticated/app/notifications'
    | '/_authenticated/app/offers'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/referrals'
    | '/_authenticated/app/rewards'
    | '/_authenticated/app/scan'
    | '/_authenticated/app/shop'
    | '/_authenticated/merchant/analytics'
    | '/_authenticated/merchant/campaigns'
    | '/_authenticated/merchant/funding'
    | '/_authenticated/merchant/integrations'
    | '/_authenticated/merchant/offers'
    | '/_authenticated/merchant/pos'
    | '/_authenticated/merchant/rewards'
    | '/_authenticated/merchant/settings'
    | '/_authenticated/merchant/team'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/merchant/'
    | '/api/public/rewards/events'
    | '/api/public/rewards/health'
    | '/api/public/rewards/scheduled-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FeaturesConsumersRoute: typeof FeaturesConsumersRoute
  FeaturesDevelopersRoute: typeof FeaturesDevelopersRoute
  FeaturesEnterpriseRoute: typeof FeaturesEnterpriseRoute
  FeaturesMerchantsRoute: typeof FeaturesMerchantsRoute
  FeaturesPartnersRoute: typeof FeaturesPartnersRoute
  FeaturesStaffRoute: typeof FeaturesStaffRoute
  LegalAccessibilityRoute: typeof LegalAccessibilityRoute
  LegalAmlRoute: typeof LegalAmlRoute
  LegalComplaintsRoute: typeof LegalComplaintsRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalGdprRoute: typeof LegalGdprRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicRewardsEventsRoute: typeof ApiPublicRewardsEventsRoute
  ApiPublicRewardsHealthRoute: typeof ApiPublicRewardsHealthRoute
  ApiPublicRewardsScheduledJobsRoute: typeof ApiPublicRewardsScheduledJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/gdpr': {
      id: '/legal/gdpr'
      path: '/legal/gdpr'
      fullPath: '/legal/gdpr'
      preLoaderRoute: typeof LegalGdprRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/complaints': {
      id: '/legal/complaints'
      path: '/legal/complaints'
      fullPath: '/legal/complaints'
      preLoaderRoute: typeof LegalComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/aml': {
      id: '/legal/aml'
      path: '/legal/aml'
      fullPath: '/legal/aml'
      preLoaderRoute: typeof LegalAmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/accessibility': {
      id: '/legal/accessibility'
      path: '/legal/accessibility'
      fullPath: '/legal/accessibility'
      preLoaderRoute: typeof LegalAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/staff': {
      id: '/features/staff'
      path: '/features/staff'
      fullPath: '/features/staff'
      preLoaderRoute: typeof FeaturesStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/partners': {
      id: '/features/partners'
      path: '/features/partners'
      fullPath: '/features/partners'
      preLoaderRoute: typeof FeaturesPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/merchants': {
      id: '/features/merchants'
      path: '/features/merchants'
      fullPath: '/features/merchants'
      preLoaderRoute: typeof FeaturesMerchantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/enterprise': {
      id: '/features/enterprise'
      path: '/features/enterprise'
      fullPath: '/features/enterprise'
      preLoaderRoute: typeof FeaturesEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/developers': {
      id: '/features/developers'
      path: '/features/developers'
      fullPath: '/features/developers'
      preLoaderRoute: typeof FeaturesDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/consumers': {
      id: '/features/consumers'
      path: '/features/consumers'
      fullPath: '/features/consumers'
      preLoaderRoute: typeof FeaturesConsumersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rewards-v4': {
      id: '/_authenticated/rewards-v4'
      path: '/rewards-v4'
      fullPath: '/rewards-v4'
      preLoaderRoute: typeof AuthenticatedRewardsV4RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards-scenario-lab': {
      id: '/_authenticated/rewards-scenario-lab'
      path: '/rewards-scenario-lab'
      fullPath: '/rewards-scenario-lab'
      preLoaderRoute: typeof AuthenticatedRewardsScenarioLabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards-production': {
      id: '/_authenticated/rewards-production'
      path: '/rewards-production'
      fullPath: '/rewards-production'
      preLoaderRoute: typeof AuthenticatedRewardsProductionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilot-operations': {
      id: '/_authenticated/pilot-operations'
      path: '/pilot-operations'
      fullPath: '/pilot-operations'
      preLoaderRoute: typeof AuthenticatedPilotOperationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant-onboarding': {
      id: '/_authenticated/merchant-onboarding'
      path: '/merchant-onboarding'
      fullPath: '/merchant-onboarding'
      preLoaderRoute: typeof AuthenticatedMerchantOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant': {
      id: '/_authenticated/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof AuthenticatedMerchantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/liability-centre': {
      id: '/_authenticated/liability-centre'
      path: '/liability-centre'
      fullPath: '/liability-centre'
      preLoaderRoute: typeof AuthenticatedLiabilityCentreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/go-live-readiness': {
      id: '/_authenticated/go-live-readiness'
      path: '/go-live-readiness'
      fullPath: '/go-live-readiness'
      preLoaderRoute: typeof AuthenticatedGoLiveReadinessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaign-studio': {
      id: '/_authenticated/campaign-studio'
      path: '/campaign-studio'
      fullPath: '/campaign-studio'
      preLoaderRoute: typeof AuthenticatedCampaignStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/merchant/': {
      id: '/_authenticated/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof AuthenticatedMerchantIndexRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/merchant/team': {
      id: '/_authenticated/merchant/team'
      path: '/team'
      fullPath: '/merchant/team'
      preLoaderRoute: typeof AuthenticatedMerchantTeamRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/settings': {
      id: '/_authenticated/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof AuthenticatedMerchantSettingsRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/rewards': {
      id: '/_authenticated/merchant/rewards'
      path: '/rewards'
      fullPath: '/merchant/rewards'
      preLoaderRoute: typeof AuthenticatedMerchantRewardsRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/pos': {
      id: '/_authenticated/merchant/pos'
      path: '/pos'
      fullPath: '/merchant/pos'
      preLoaderRoute: typeof AuthenticatedMerchantPosRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/offers': {
      id: '/_authenticated/merchant/offers'
      path: '/offers'
      fullPath: '/merchant/offers'
      preLoaderRoute: typeof AuthenticatedMerchantOffersRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/integrations': {
      id: '/_authenticated/merchant/integrations'
      path: '/integrations'
      fullPath: '/merchant/integrations'
      preLoaderRoute: typeof AuthenticatedMerchantIntegrationsRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/funding': {
      id: '/_authenticated/merchant/funding'
      path: '/funding'
      fullPath: '/merchant/funding'
      preLoaderRoute: typeof AuthenticatedMerchantFundingRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/campaigns': {
      id: '/_authenticated/merchant/campaigns'
      path: '/campaigns'
      fullPath: '/merchant/campaigns'
      preLoaderRoute: typeof AuthenticatedMerchantCampaignsRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/merchant/analytics': {
      id: '/_authenticated/merchant/analytics'
      path: '/analytics'
      fullPath: '/merchant/analytics'
      preLoaderRoute: typeof AuthenticatedMerchantAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMerchantRoute
    }
    '/_authenticated/app/shop': {
      id: '/_authenticated/app/shop'
      path: '/shop'
      fullPath: '/app/shop'
      preLoaderRoute: typeof AuthenticatedAppShopRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/scan': {
      id: '/_authenticated/app/scan'
      path: '/scan'
      fullPath: '/app/scan'
      preLoaderRoute: typeof AuthenticatedAppScanRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rewards': {
      id: '/_authenticated/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AuthenticatedAppRewardsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/referrals': {
      id: '/_authenticated/app/referrals'
      path: '/referrals'
      fullPath: '/app/referrals'
      preLoaderRoute: typeof AuthenticatedAppReferralsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/offers': {
      id: '/_authenticated/app/offers'
      path: '/offers'
      fullPath: '/app/offers'
      preLoaderRoute: typeof AuthenticatedAppOffersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/notifications': {
      id: '/_authenticated/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AuthenticatedAppNotificationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nearby': {
      id: '/_authenticated/app/nearby'
      path: '/nearby'
      fullPath: '/app/nearby'
      preLoaderRoute: typeof AuthenticatedAppNearbyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/claim': {
      id: '/_authenticated/app/claim'
      path: '/claim'
      fullPath: '/app/claim'
      preLoaderRoute: typeof AuthenticatedAppClaimRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/badges': {
      id: '/_authenticated/app/badges'
      path: '/badges'
      fullPath: '/app/badges'
      preLoaderRoute: typeof AuthenticatedAppBadgesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/merchants': {
      id: '/_authenticated/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AuthenticatedAdminMerchantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/claims': {
      id: '/_authenticated/admin/claims'
      path: '/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AuthenticatedAdminClaimsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/rewards/scheduled-jobs': {
      id: '/api/public/rewards/scheduled-jobs'
      path: '/api/public/rewards/scheduled-jobs'
      fullPath: '/api/public/rewards/scheduled-jobs'
      preLoaderRoute: typeof ApiPublicRewardsScheduledJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rewards/health': {
      id: '/api/public/rewards/health'
      path: '/api/public/rewards/health'
      fullPath: '/api/public/rewards/health'
      preLoaderRoute: typeof ApiPublicRewardsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rewards/events': {
      id: '/api/public/rewards/events'
      path: '/api/public/rewards/events'
      fullPath: '/api/public/rewards/events'
      preLoaderRoute: typeof ApiPublicRewardsEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminClaimsRoute: typeof AuthenticatedAdminClaimsRoute
  AuthenticatedAdminMerchantsRoute: typeof AuthenticatedAdminMerchantsRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminClaimsRoute: AuthenticatedAdminClaimsRoute,
  AuthenticatedAdminMerchantsRoute: AuthenticatedAdminMerchantsRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRoute
  AuthenticatedAppBadgesRoute: typeof AuthenticatedAppBadgesRoute
  AuthenticatedAppClaimRoute: typeof AuthenticatedAppClaimRoute
  AuthenticatedAppNearbyRoute: typeof AuthenticatedAppNearbyRoute
  AuthenticatedAppNotificationsRoute: typeof AuthenticatedAppNotificationsRoute
  AuthenticatedAppOffersRoute: typeof AuthenticatedAppOffersRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppReferralsRoute: typeof AuthenticatedAppReferralsRoute
  AuthenticatedAppRewardsRoute: typeof AuthenticatedAppRewardsRoute
  AuthenticatedAppScanRoute: typeof AuthenticatedAppScanRoute
  AuthenticatedAppShopRoute: typeof AuthenticatedAppShopRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRoute,
  AuthenticatedAppBadgesRoute: AuthenticatedAppBadgesRoute,
  AuthenticatedAppClaimRoute: AuthenticatedAppClaimRoute,
  AuthenticatedAppNearbyRoute: AuthenticatedAppNearbyRoute,
  AuthenticatedAppNotificationsRoute: AuthenticatedAppNotificationsRoute,
  AuthenticatedAppOffersRoute: AuthenticatedAppOffersRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppReferralsRoute: AuthenticatedAppReferralsRoute,
  AuthenticatedAppRewardsRoute: AuthenticatedAppRewardsRoute,
  AuthenticatedAppScanRoute: AuthenticatedAppScanRoute,
  AuthenticatedAppShopRoute: AuthenticatedAppShopRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedMerchantRouteChildren {
  AuthenticatedMerchantAnalyticsRoute: typeof AuthenticatedMerchantAnalyticsRoute
  AuthenticatedMerchantCampaignsRoute: typeof AuthenticatedMerchantCampaignsRoute
  AuthenticatedMerchantFundingRoute: typeof AuthenticatedMerchantFundingRoute
  AuthenticatedMerchantIntegrationsRoute: typeof AuthenticatedMerchantIntegrationsRoute
  AuthenticatedMerchantOffersRoute: typeof AuthenticatedMerchantOffersRoute
  AuthenticatedMerchantPosRoute: typeof AuthenticatedMerchantPosRoute
  AuthenticatedMerchantRewardsRoute: typeof AuthenticatedMerchantRewardsRoute
  AuthenticatedMerchantSettingsRoute: typeof AuthenticatedMerchantSettingsRoute
  AuthenticatedMerchantTeamRoute: typeof AuthenticatedMerchantTeamRoute
  AuthenticatedMerchantIndexRoute: typeof AuthenticatedMerchantIndexRoute
}

const AuthenticatedMerchantRouteChildren: AuthenticatedMerchantRouteChildren = {
  AuthenticatedMerchantAnalyticsRoute: AuthenticatedMerchantAnalyticsRoute,
  AuthenticatedMerchantCampaignsRoute: AuthenticatedMerchantCampaignsRoute,
  AuthenticatedMerchantFundingRoute: AuthenticatedMerchantFundingRoute,
  AuthenticatedMerchantIntegrationsRoute:
    AuthenticatedMerchantIntegrationsRoute,
  AuthenticatedMerchantOffersRoute: AuthenticatedMerchantOffersRoute,
  AuthenticatedMerchantPosRoute: AuthenticatedMerchantPosRoute,
  AuthenticatedMerchantRewardsRoute: AuthenticatedMerchantRewardsRoute,
  AuthenticatedMerchantSettingsRoute: AuthenticatedMerchantSettingsRoute,
  AuthenticatedMerchantTeamRoute: AuthenticatedMerchantTeamRoute,
  AuthenticatedMerchantIndexRoute: AuthenticatedMerchantIndexRoute,
}

const AuthenticatedMerchantRouteWithChildren =
  AuthenticatedMerchantRoute._addFileChildren(
    AuthenticatedMerchantRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCampaignStudioRoute: typeof AuthenticatedCampaignStudioRoute
  AuthenticatedGoLiveReadinessRoute: typeof AuthenticatedGoLiveReadinessRoute
  AuthenticatedLiabilityCentreRoute: typeof AuthenticatedLiabilityCentreRoute
  AuthenticatedMerchantRoute: typeof AuthenticatedMerchantRouteWithChildren
  AuthenticatedMerchantOnboardingRoute: typeof AuthenticatedMerchantOnboardingRoute
  AuthenticatedPilotOperationsRoute: typeof AuthenticatedPilotOperationsRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedRewardsProductionRoute: typeof AuthenticatedRewardsProductionRoute
  AuthenticatedRewardsScenarioLabRoute: typeof AuthenticatedRewardsScenarioLabRoute
  AuthenticatedRewardsV4Route: typeof AuthenticatedRewardsV4Route
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCampaignStudioRoute: AuthenticatedCampaignStudioRoute,
  AuthenticatedGoLiveReadinessRoute: AuthenticatedGoLiveReadinessRoute,
  AuthenticatedLiabilityCentreRoute: AuthenticatedLiabilityCentreRoute,
  AuthenticatedMerchantRoute: AuthenticatedMerchantRouteWithChildren,
  AuthenticatedMerchantOnboardingRoute: AuthenticatedMerchantOnboardingRoute,
  AuthenticatedPilotOperationsRoute: AuthenticatedPilotOperationsRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedRewardsProductionRoute: AuthenticatedRewardsProductionRoute,
  AuthenticatedRewardsScenarioLabRoute: AuthenticatedRewardsScenarioLabRoute,
  AuthenticatedRewardsV4Route: AuthenticatedRewardsV4Route,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  FeaturesConsumersRoute: FeaturesConsumersRoute,
  FeaturesDevelopersRoute: FeaturesDevelopersRoute,
  FeaturesEnterpriseRoute: FeaturesEnterpriseRoute,
  FeaturesMerchantsRoute: FeaturesMerchantsRoute,
  FeaturesPartnersRoute: FeaturesPartnersRoute,
  FeaturesStaffRoute: FeaturesStaffRoute,
  LegalAccessibilityRoute: LegalAccessibilityRoute,
  LegalAmlRoute: LegalAmlRoute,
  LegalComplaintsRoute: LegalComplaintsRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalGdprRoute: LegalGdprRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicRewardsEventsRoute: ApiPublicRewardsEventsRoute,
  ApiPublicRewardsHealthRoute: ApiPublicRewardsHealthRoute,
  ApiPublicRewardsScheduledJobsRoute: ApiPublicRewardsScheduledJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
